const quizData = [
    // === BATCH 1 ===
    { q: "What is the primary focus of Human Resource Management (HRM)?", o: ["Increasing market share", "Budget allocation", "Customer acquisition", "Deployment and development of employees"], a: 3 },
    { q: "Which of the following was the previous name for Human Resource Management?", o: ["Human Capital Office", "Human Development Unit", "Personnel Department", "People Operations"], a: 2 },
    { q: "One major difference between Personnel Management and HRM is that:", o: ["HRM is less strategic", "Personnel Management focuses on profit", "Personnel Management integrates training with values", "HRM integrates training with company values"], a: 3 },
    { q: "Recruitment is best described as:", o: ["Promoting employees", "Training staff", "Identifying and attracting candidates", "Transferring staff"], a: 2 },
    { q: "Which of the following is a source of internal recruitment?", o: ["Transfers", "Employment agencies", "Walk-in interviews", "Online job portals"], a: 0 },
    { q: "One merit of internal recruitment is:", o: ["High cost", "Limited candidate pool", "Low training cost", "Uncertain response"], a: 2 },
    { q: "A disadvantage of internal recruitment is to:", o: ["Boosts morale", "Encourages loyalty", "May encourage favoritism", "Provides fresh ideas"], a: 2 },
    { q: "Direct recruitment is a type of:", o: ["External source", "Internal source", "On-the-job training", "Staff evaluation"], a: 0 },
    { q: "A benefit of external recruitment is:", o: ["Higher internal morale", "Wider choice of candidates", "More favoritism", "Faster placement"], a: 1 },
    { q: "One drawback of external recruitment is:", o: ["Low cost", "Uncertain response", "Guaranteed satisfaction", "Fast decision-making"], a: 1 },
    { q: "E-recruitment is an example of:", o: ["Recent trend in recruitment", "Traditional hiring", "External promotion", "Staff reassignment"], a: 0 },
    { q: "Selection is often called a negative process because:", o: ["It involves rejection of candidates", "It accepts all applicants", "It promotes all employees", "It is a cost-saving step"], a: 0 },
    { q: "Proper placement helps reduce:", o: ["Workload", "Customer dissatisfaction", "Labour turnover", "Recruitment needs"], a: 2 },
    { q: "One consideration in placement is:", o: ["Retirement age", "Job requirements", "Resignation notice", "Product knowledge"], a: 1 },
    { q: "Manpower planning is essential for:", o: ["Improving customer loyalty", "Forecasting employee needs", "Product development", "Budgeting finances"], a: 1 },

    // === BATCH 2 ===
    { q: "The manpower inventory process includes:", o: ["Employee dismissal", "Data collection on current workforce", "Retrenchment notices", "External advertisements"], a: 1 },
    { q: "A key benefit of manpower planning is:", o: ["Job enlargement", "Cost minimization", "Maximizing human resource use", "Staff transfer"], a: 1 },
    { q: "An approach to manpower forecasting is:", o: ["Administrator opinion", "Informal interviews", "Customer feedback", "Daily meetings"], a: 1 },
    { q: "A failure of poor manpower planning is:", o: ["Reduced wages", "Reactive corporate strategy", "Higher productivity", "Clear job roles"], a: 1 },
    { q: "One common cause of communication breakdown is:", o: ["Open expression", "Overloading", "Shared vision", "Clear instructions"], a: 1 },
    { q: "Orientation helps reduce:", o: ["Costs", "Projects", "Employee turnover", "Salaries"], a: 2 },
    { q: "Intrinsic motivation leads to:", o: ["Self-driven performance", "Demotivation", "External rewards", "Task avoidance"], a: 0 },
    { q: "One major HRIS function is:", o: ["Salary administration", "Fundraising", "Product innovation", "Social media marketing"], a: 0 },
    { q: "HRM contributes to strategic planning by:", o: ["Supporting employee systems", "Replacing departments", "Designing products", "Conducting external audits"], a: 0 },
    { q: "Employee placement ensures:", o: ["Matching job with employee ability", "Random job allocation", "Delayed hiring", "Managerial dispute"], a: 0 },
    { q: "A successful manpower forecast requires:", o: ["Guesswork", "Data-based prediction", "Managerial opinion only", "Ignoring job roles"], a: 1 },
    { q: "What does the selection process ultimately lead to in an organization?", o: ["Rejection of applications", "Employment of suitable workers", "Promotion of staff", "Salary negotiation"], a: 1 },
    { q: "Which of the following is not a source of external recruitment?", o: ["Casual callers", "Employment agencies", "Transfers", "Campus recruitment"], a: 2 },
    { q: "Which internal source of recruitment involves shifting an employee without changing responsibility?", o: ["Transfer", "Promotion", "Retirement", "Contracting"], a: 0 },
    { q: "Which of the following is a recent trend in recruitment?", o: ["Manual application", "Internal memoranda", "Walk-in interviews", "Labour union referral"], a: 2 },

    // === BATCH 3 ===
    { q: "Which of the following is not a merit of internal recruitment?", o: ["Low cost", "Motivates staff", "Wider talent pool", "Promotes morale"], a: 2 },
    { q: "What is a key function of Human Resource Management in modern organizations?", o: ["Preparing company budgets", "Developing and retaining talent", "Selling company shares", "Managing customer feedback"], a: 1 },
    { q: "The process of placing a selected candidate on the right job is known as:", o: ["Orientation", "Selection", "Placement", "Training"], a: 2 },
    { q: "Which recruitment source offers fresh talent and competitive spirit?", o: ["Internal source", "External source", "Transfer", "Promotion"], a: 1 },
    { q: "A job that offers higher pay and status is filled through:", o: ["Demotion", "Transfer", "Promotion", "Casual call"], a: 2 },
    { q: "Which of the following is a demerit of external recruitment?", o: ["Staff diversity", "Costly process", "Fresh ideas", "Talent infusion"], a: 1 },
    { q: "Which planning approach links human resources with organizational strategy?", o: ["Daily planning", "Operational budgeting", "Manpower planning", "Shift scheduling"], a: 2 },
    { q: "The process of data-based estimation of future staffing needs is known as:", o: ["Staff rotation", "Manpower forecast", "Skill outsourcing", "Job review"], a: 1 },
    { q: "What describes a mismatch in manpower planning outcomes?", o: ["Accurate forecasting", "Corporate anarchy", "Targeted hiring", "Balanced allocation"], a: 1 },
    { q: "Macro-level manpower planning focuses primarily on:", o: ["Individual companies", "National workforce needs", "Private investors", "Departmental targets"], a: 1 },
    { q: "Manpower planning enables an organization to:", o: ["Avoid hiring", "Identify skill gaps", "Ignore training", "Automate tasks"], a: 1 },
    { q: "Which of these is a benefit of manpower planning?", o: ["Redundancy creation", "Development of employee skills", "Staff stagnation", "Decreased staff commitment"], a: 1 },
    { q: "Training improves productivity mainly because it:", o: ["Increases equipment", "Minimizes targets", "Enhances employee skillset", "Reduces salaries"], a: 2 },
    { q: "Training that helps employees adapt to new machines is driven by:", o: ["Management policy", "Technological change", "Sales decline", "Legal obligation"], a: 1 },
    { q: "What is the link between training and safety?", o: ["Delays job completion", "Encourages mistakes", "Reduces industrial accidents", "Lowers productivity"], a: 2 },

    // === BATCH 4 ===
    { q: "Which is not a direct benefit of training to employees?", o: ["Increased confidence", "Skill acquisition", "Longer hours", "High earnings potential"], a: 2 },
    { q: "What motivates employees intrinsically?", o: ["Personal fulfillment", "Bonuses", "Promotions", "Allowances"], a: 0 },
    { q: "Which job design strategy periodically moves employees across roles?", o: ["Job simplification", "Job rotation", "Job loading", "Job withdrawal"], a: 1 },
    { q: "The concept of 'task identity' in the Job Characteristics Model refers to:", o: ["Number of team members", "Uniform job descriptions", "Contribution to a complete project", "Staff hierarchy"], a: 2 },
    { q: "In open-book management, employers must:", o: ["Hire new accountants", "Keep records secret", "Share financial data with staff", "Hide expenses"], a: 2 },
    { q: "Which of the following improves employee loyalty and reduces stress?", o: ["Resignation policy", "Effective orientation", "Weekly training", "Wage freeze"], a: 1 },
    { q: "Accommodation in socialization is when:", o: ["Employees resign", "Policies are set", "Newcomers adjust to reality", "Salary is reviewed"], a: 2 },
    { q: "A benefit of employee socialization is:", o: ["Reduced work hours", "Increased integration", "Less supervision", "Salary increase"], a: 1 },
    { q: "Communication enables organizations to:", o: ["Train clients", "Coordinate activities", "Conduct sales", "Reduce pay"], a: 1 },
    { q: "An example of electronic communication is:", o: ["Memo", "Letter", "E-mail", "Telephone call"], a: 2 },
    { q: "Which part of the communication process involves choosing how to send a message?", o: ["Decoding", "Feedback", "Encoding", "Reception"], a: 2 },
    { q: "In communication, 'noise' refers to:", o: ["Phone calls", "Message interference", "Time delays", "Poor equipment"], a: 1 },
    { q: "A common cause of communication failure is:", o: ["Managerial skill", "Perception differences", "High education", "Wage disputes"], a: 1 },
    { q: "One way to overcome communication overload is to:", o: ["Block feedback", "Filter messages", "Use slang", "Encourage multitasking"], a: 1 },
